# NumPy

Numpy é um pacote do Python que nos permite trabalhar com arrays (listas) e matrizes (listas multidimensionais) de forma eficiente, possuindo uma extensa coleção de funções matemáticas para trabalhar com essas duas estruturas.

In [1]:
import numpy as np

## Criando Arrays

**`numpy.array(lista)`** nos permite converter um array tradicional passado como parâmetro para um array do NumPy, permitindo assim o uso de todos os recurso oferecidos pelo pacote.

In [2]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [3]:
y = np.array([1, 2, 3])
y

array([1, 2, 3])

In [4]:
# Passando como parâmetro um array multidimensional.
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

**`.shape`** é um atributo que retorna as dimensões do array.

In [5]:
m.shape

(2, 3)

**`numpy.arrange(início, fim, tamanho_do_passo)`** gera um array da numpy com os valores do intervalo entre início e fim-1 espaçados pelo tamanho do passo.

In [6]:
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

**`.reshape(m, n)`** retorna uma cópia do array com as dimensões ajustadas para m X n.

In [7]:
n = n.reshape(3, 5) # Alterou as dimensões de n de 1 X 15 para 3 X 5.
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

**`np.linspace(a, b, n)`** gera um array com **n** elementos entre **a** e **b**, distribuindo os valores igualmente.

In [8]:
o = np.linspace(0, 4, 9) # Um array de 9 números entre 0 e quatro.
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

**`.resize(m, n)`** Altera as dimensões de um array para m X n.

In [9]:
o.resize(3, 3) # O array o passou de 0 X 9 para 3 X 3.
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

**`numpy.ones(dimensões)`** cria um array de uns (em ponto flutuante por padrão).

In [12]:
np.ones((3, 2)) # Gera um array de uns com dimensões 3 X 2.

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
p = np.ones([2, 3], int) # Array de 1's inteiros com dimensões 2 X 3.
p

array([[1, 1, 1],
       [1, 1, 1]])

**`numpy.zeros((dimensões))`** cria um array de zeros (em ponto flutuante por padrão).

In [13]:
np.zeros((2, 3)) # Gera um array de zeros com dimensões 2 X 3.

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros([3, 2], int) # Array de 0's inteiros com dimensões 3 X 2.

array([[0, 0],
       [0, 0],
       [0, 0]])

**numpy.eye(dimensão)** cria o array de uma matriz identidade.

In [14]:
np.eye(3) # Gera uma matriz identidade 3 X 3.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**`numpy.diag(array)`** cria uma matriz diagonal com os valores do array passado como parâmetro.

In [15]:
y = [1, 2, 3]
np.diag(y)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

Podemos gerar um array de números repetidos usando o operador *.

In [ ]:
# Essa é uma forma de gerar um array de valores repetidos.
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

**`numpy.repeat(array, repetições)`** cria um array de números repetidos. Ao contrário do exemplo acima, a ordem dos repetidos é de acordo com os elementos originais.

In [16]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

**`numpy.vstack(lista de arrays)`** cria um array que enpilha verticalmente a lista de arrays passados.

In [20]:
np.vstack([p, p*2])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

**numpy.hstack(lista de arrays)** cria um array que empilha horizontalmente a lista de arrays passados.

In [21]:
np.hstack([p, p*2])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Operações

In [ ]:
x + y

array([2, 4, 6])

In [ ]:
x - y

array([0, 0, 0])

In [ ]:
x * y

array([1, 4, 9])

In [ ]:
x / y

array([ 1.,  1.,  1.])

In [ ]:
x ** 2

array([1, 4, 9])

In [ ]:
# Calcula o produto escalar entre dois vetores (dot product).
x.dot(y)

14

In [ ]:
z = np.array([y, y**2])
z

array([[1, 2, 3],
       [1, 4, 9]])

In [ ]:
z.shape

(2, 3)

In [ ]:
# Esse método retorna a transposta do array.
z.T

array([[1, 1],
       [2, 4],
       [3, 9]])

In [ ]:
z.T.shape

(3, 2)

In [ ]:
# Retorna os tipos de valores que o array tem.
z.dtype

dtype('int64')

In [ ]:
# Converte o tipo dos valores do array para o do parâmetro fornecido.
z = z.astype('f')
z.dtype

dtype('float32')

In [ ]:
a = np.array([-4, -2, 1, 3, 5])

In [ ]:
# Retorna a soma de todos os elemntos do array.
a.sum()

3

In [ ]:
# Retorna o valor máximo do array.
a.max()

5

In [ ]:
# Retorna o valor mínimo do array.
a.min()

-4

In [ ]:
# Retorna a média dos valores do array.
a.mean()

0.59999999999999998

In [ ]:
# Retorna o desvio padrão dos valores do array.
a.std()

3.2619012860600183

In [ ]:
# Retorna o índice (posição) do valor máximo do array.
a.argmax()

4

In [ ]:
# Retorna o índice (posição) do valor mínimo do array.
a.argmin()

0

## Indexing / Slicing

In [ ]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [ ]:
# Slicing usa o notação : para obter um intervalo de valores.
# Os parâmetros são o índice de partida e o índice de parada.
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4]))

In [ ]:
# Aqui pegamos os valores entre o índice 1 e o 5 (exclusive).
s[1:5]

array([ 1,  4,  9, 16])

In [ ]:
# Também podemos usar números negativos para pegar os valores
# a partir da outra ponta do array.
s[-4:]

array([ 81, 100, 121, 144])

In [ ]:
# O terceiro parâmetro é a quantidade de passos.
# No exemplo abaixo estamos indo da posição -5 (8) até o início de 2 em 2 de trás para frente.
s[-5::-2]

array([64, 36, 16,  4,  0])

In [ ]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
r[2, 2]

14

In [ ]:
r[3, 3:6]

array([21, 22, 23])

In [ ]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [ ]:
r[-1,::2]

array([30, 32, 34])

In [ ]:
# Também podemos usar o operador [] para buscas condicionais.
r[r > 31]

array([32, 33, 34, 35])

In [ ]:
r[r > 12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30, 31, 32, 33, 34, 35])

In [ ]:
# Também podemos usar o operador de atribuição = com o operador [].
# Abaixo substituímos todos os elementos de r maiores que 30 por 30,
# limitando assim seu valor máximo para 30.
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [ ]:
# Pegamos uma fatia do array r e colocamos em r2.
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [ ]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# Olhando o resultado abaixo, podemos ver que as posições de r
# passadas para r2 também foram alteradas, o que devemos tomar cuidado.
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [ ]:
# Para gerarmos uma cópia de um array da numpy devemos usar o método copy().
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [ ]:
# Podemos ver agora que se fizermos qualquer alteração em r_copy,
# o array r permanecerá inalterado.
r_copy[:] = 10
print(r_copy)
print()
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


## Iterando sobre arrays

In [ ]:
# Gera um array de números aleatórios dentro de um intervalo.
# Início do intervalo, tamanho do intervalo, dimensões do array.
test = np.random.randint(0, 10, (4, 3))
test

array([[8, 9, 0],
       [4, 4, 2],
       [4, 7, 6],
       [2, 1, 6]])

In [ ]:
# Iterando por linha.
for row in test:
    print(row)

[8 9 0]
[4 4 2]
[4 7 6]
[2 1 6]


In [ ]:
# Outra forma de iterar por linha.
for i in range(len(test)):
    print(test[i])

[8 9 0]
[4 4 2]
[4 7 6]
[2 1 6]


In [ ]:
# enumerate(array) enumera o array.
# No exemplo abaixo itera o índice da linha e o valor da mesma.
for i, row in enumerate(test):
    print('row {} is {}'.format(i, row))

row 0 is [8 9 0]
row 1 is [4 4 2]
row 2 is [4 7 6]
row 3 is [2 1 6]


In [ ]:
test2 = test ** 2
test2

array([[64, 81,  0],
       [16, 16,  4],
       [16, 49, 36],
       [ 4,  1, 36]])

In [ ]:
# A função zip permite iteração entre dois ou mais arrays.
for i, j in zip(test, test2):
    print('{} + {} = {}'.format(i, j, i + j))

[8 9 0] + [64 81  0] = [72 90  0]
[4 4 2] + [16 16  4] = [20 20  6]
[4 7 6] + [16 49 36] = [20 56 42]
[2 1 6] + [ 4  1 36] = [ 6  2 42]


In [ ]:
arr = np.array([1, 7, 14, 21, 28, 35])
arr

array([ 1,  7, 14, 21, 28, 35])

In [ ]:
r = np.diag(arr)
r

array([[ 1,  0,  0,  0,  0,  0],
       [ 0,  7,  0,  0,  0,  0],
       [ 0,  0, 14,  0,  0,  0],
       [ 0,  0,  0, 21,  0,  0],
       [ 0,  0,  0,  0, 28,  0],
       [ 0,  0,  0,  0,  0, 35]])

In [ ]:
r.reshape(36)[::7]

array([ 1,  7, 14, 21, 28, 35])