# Numpy

In [4]:
import numpy as np

# Creating Arrays

In [5]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [6]:
y = np.array([1, 2, 3])
y

array([1, 2, 3])

In [7]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [8]:
m.shape # Retorna as dimensões do array.

(2, 3)

In [9]:
# Gera um array com os valores pares espaçados por um dado intervalo.
# np.arange(início, tamanho_do_array, tamanho_do_passo)
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [10]:
n = n.reshape(3, 5) # Converte um array de uma dimensão para um de m X n dimensões.
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [11]:
# Faz quase o mesmo que a função arange, só que recebe
# como último parâmetro quantos números são desejados e
# o intervalo é dividido de acordo.
o = np.linspace(0, 4, 9)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [12]:
# Altera as dimensões do array (como o reshape).
o.resize(3, 3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [13]:
# Gera um array de 1's (em ponto flutuante por padrão).
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [14]:
# Gera um array de zeros (em ponto flutuante por padrão).
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [15]:
# Gera um array representando uma matriz identidade (1 na diagonal e 0 nos demais pontos).
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [16]:
# Gera um array representando uma matriz diagonal (os valores e dimensões são definidos pelo array passado).
np.diag(y)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [17]:
# Essa é uma forma de gerar um array de valores repetidos.
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [18]:
# Essa é outra forma de gerar array de valores repetidos (note a diferença entre ambos os arrays gerados).
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [19]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
# Gera um array que é uma pilha vertical dos arrays passados por parâmetro.
np.vstack([p, p*2])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [21]:
# Gera um array que é uma pilha horizontal dos arrays passados por parâmetro
np.hstack([p, p*2])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations

In [22]:
x + y

array([2, 4, 6])

In [23]:
x - y

array([0, 0, 0])

In [24]:
x * y

array([1, 4, 9])

In [25]:
x / y

array([ 1.,  1.,  1.])

In [26]:
x ** 2

array([1, 4, 9])

In [27]:
# Calcula o produto escalar entre dois vetores (dot product).
x.dot(y)

14

In [28]:
z = np.array([y, y**2])
z

array([[1, 2, 3],
       [1, 4, 9]])

In [29]:
z.shape

(2, 3)

In [30]:
# Esse método retorna a transposta do array.
z.T

array([[1, 1],
       [2, 4],
       [3, 9]])

In [31]:
z.T.shape

(3, 2)

In [32]:
# Retorna os tipos de valores que o array tem.
z.dtype

dtype('int64')

In [33]:
# Converte o tipo dos valores do array para o do parâmetro fornecido.
z = z.astype('f')
z.dtype

dtype('float32')

In [34]:
a = np.array([-4, -2, 1, 3, 5])

In [35]:
# Retorna a soma de todos os elemntos do array.
a.sum()

3

In [36]:
# Retorna o valor máximo do array.
a.max()

5

In [37]:
# Retorna o valor mínimo do array.
a.min()

-4

In [38]:
# Retorna a média dos valores do array.
a.mean()

0.59999999999999998

In [39]:
# Retorna o desvio padrão dos valores do array.
a.std()

3.2619012860600183

In [40]:
# Retorna o índice (posição) do valor máximo do array.
a.argmax()

4

In [41]:
# Retorna o índice (posição) do valor mínimo do array.
a.argmin()

0

# Indexing / Slicing

In [42]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [43]:
# Slicing usa o notação : para obter um intervalo de valores.
# Os parâmetros são o índice de partida e o índice de parada.
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4]))

In [44]:
# Aqui pegamos os valores entre o índice 1 e o 5 (exclusive).
s[1:5]

array([ 1,  4,  9, 16])

In [45]:
# Também podemos usar números negativos para pegar os valores
# a partir da outra ponta do array.
s[-4:]

array([ 81, 100, 121, 144])

In [46]:
# O terceiro parâmetro é a quantidade de passos.
# No exemplo abaixo estamos indo da posição -5 (8) até o início de 2 em 2 de trás para frente.
s[-5::-2]

array([64, 36, 16,  4,  0])

In [47]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [48]:
r[2, 2]

14

In [49]:
r[3, 3:6]

array([21, 22, 23])

In [50]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [51]:
r[-1,::2]

array([30, 32, 34])

In [52]:
# Também podemos usar o operador [] para buscas condicionais.
r[r > 31]

array([32, 33, 34, 35])

In [53]:
r[r > 12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30, 31, 32, 33, 34, 35])

In [54]:
# Também podemos usar o operador de atribuição = com o operador [].
# Abaixo substituímos todos os elementos de r maiores que 30 por 30,
# limitando assim seu valor máximo para 30.
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [55]:
# Pegamos uma fatia do array r e colocamos em r2.
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [56]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [57]:
# Olhando o resultado abaixo, podemos ver que as posições de r
# passadas para r2 também foram alteradas, o que devemos tomar cuidado.
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [58]:
# Para gerarmos uma cópia de um array da numpy devemos usar o método copy().
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [59]:
# Podemos ver agora que se fizermos qualquer alteração em r_copy,
# o array r permanecerá inalterado.
r_copy[:] = 10
print(r_copy)
print()
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


# Iterating over arrays

In [60]:
# Gera um array de números aleatórios dentro de um intervalo.
# Início do intervalo, tamanho do intervalo, dimensões do array.
test = np.random.randint(0, 10, (4, 3))
test

array([[8, 9, 0],
       [4, 4, 2],
       [4, 7, 6],
       [2, 1, 6]])

In [61]:
# Iterando por linha.
for row in test:
    print(row)

[8 9 0]
[4 4 2]
[4 7 6]
[2 1 6]


In [62]:
# Outra forma de iterar por linha.
for i in range(len(test)):
    print(test[i])

[8 9 0]
[4 4 2]
[4 7 6]
[2 1 6]


In [63]:
# enumerate(array) enumera o array.
# No exemplo abaixo itera o índice da linha e o valor da mesma.
for i, row in enumerate(test):
    print('row {} is {}'.format(i, row))

row 0 is [8 9 0]
row 1 is [4 4 2]
row 2 is [4 7 6]
row 3 is [2 1 6]


In [64]:
test2 = test ** 2
test2

array([[64, 81,  0],
       [16, 16,  4],
       [16, 49, 36],
       [ 4,  1, 36]])

In [65]:
# A função zip permite iteração entre dois ou mais arrays.
for i, j in zip(test, test2):
    print('{} + {} = {}'.format(i, j, i + j))

[8 9 0] + [64 81  0] = [72 90  0]
[4 4 2] + [16 16  4] = [20 20  6]
[4 7 6] + [16 49 36] = [20 56 42]
[2 1 6] + [ 4  1 36] = [ 6  2 42]


In [66]:
arr = np.array([1, 7, 14, 21, 28, 35])
arr

array([ 1,  7, 14, 21, 28, 35])

In [67]:
r = np.diag(arr)
r

array([[ 1,  0,  0,  0,  0,  0],
       [ 0,  7,  0,  0,  0,  0],
       [ 0,  0, 14,  0,  0,  0],
       [ 0,  0,  0, 21,  0,  0],
       [ 0,  0,  0,  0, 28,  0],
       [ 0,  0,  0,  0,  0, 35]])

In [68]:
r.reshape(36)[::7]

array([ 1,  7, 14, 21, 28, 35])